spring:
  application:
    name: training-system
  datasource:
    url: jdbc:postgresql://localhost:5432/word_train
    username: postgres
    password: 345
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      id:
          new_generator_mappings: false
    show-sql: true